CREATE TABLE `active_drivers` (

`id` BIGINT(20)UNSIGNED NOT NULL AUTO_INCREMENT,
 
`drivers_id` BIGINT(20) UNSIGNED NOT NULL,

`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY(`id`),
CONSTRAINT `active_drivers_drivers_foreign`
FOREIGN KEY(`drivers_id`) REFERENCES `lines`(`id`)

)DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;
